import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Intraday Goal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/pricing">
        <a className="p-4 underline text-blue-500">
          Pricing
        </a>
      </Link>
    </div>
  )
}
